/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.autoscaling.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Specification of the checkpoint. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status.
 */
@ApiModel(description = "Specification of the checkpoint. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-02T17:31:04.907Z[Etc/UTC]")
public class V1beta2VerticalPodAutoscalerCheckpointSpec {
  public static final String SERIALIZED_NAME_CONTAINER_NAME = "containerName";
  @SerializedName(SERIALIZED_NAME_CONTAINER_NAME)
  private String containerName;

  public static final String SERIALIZED_NAME_VPA_OBJECT_NAME = "vpaObjectName";
  @SerializedName(SERIALIZED_NAME_VPA_OBJECT_NAME)
  private String vpaObjectName;


  public V1beta2VerticalPodAutoscalerCheckpointSpec containerName(String containerName) {

    this.containerName = containerName;
    return this;
  }

   /**
   * Name of the checkpointed container.
   * @return containerName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name of the checkpointed container.")

  public String getContainerName() {
    return containerName;
  }


  public void setContainerName(String containerName) {
    this.containerName = containerName;
  }


  public V1beta2VerticalPodAutoscalerCheckpointSpec vpaObjectName(String vpaObjectName) {

    this.vpaObjectName = vpaObjectName;
    return this;
  }

   /**
   * Name of the VPA object that stored VerticalPodAutoscalerCheckpoint object.
   * @return vpaObjectName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name of the VPA object that stored VerticalPodAutoscalerCheckpoint object.")

  public String getVpaObjectName() {
    return vpaObjectName;
  }


  public void setVpaObjectName(String vpaObjectName) {
    this.vpaObjectName = vpaObjectName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta2VerticalPodAutoscalerCheckpointSpec v1beta2VerticalPodAutoscalerCheckpointSpec = (V1beta2VerticalPodAutoscalerCheckpointSpec) o;
    return Objects.equals(this.containerName, v1beta2VerticalPodAutoscalerCheckpointSpec.containerName) &&
        Objects.equals(this.vpaObjectName, v1beta2VerticalPodAutoscalerCheckpointSpec.vpaObjectName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(containerName, vpaObjectName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta2VerticalPodAutoscalerCheckpointSpec {\n");
    sb.append("    containerName: ").append(toIndentedString(containerName)).append("\n");
    sb.append("    vpaObjectName: ").append(toIndentedString(vpaObjectName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

