/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.autoscaling.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;

/**
 * Checkpoint of histogram for consumption of memory.
 */
@ApiModel(description = "Checkpoint of histogram for consumption of memory.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-02T17:31:04.907Z[Etc/UTC]")
public class V1beta2VerticalPodAutoscalerCheckpointStatusMemoryHistogram {
  public static final String SERIALIZED_NAME_BUCKET_WEIGHTS = "bucketWeights";
  @SerializedName(SERIALIZED_NAME_BUCKET_WEIGHTS)
  private Object bucketWeights;

  public static final String SERIALIZED_NAME_REFERENCE_TIMESTAMP = "referenceTimestamp";
  @SerializedName(SERIALIZED_NAME_REFERENCE_TIMESTAMP)
  private Object referenceTimestamp;

  public static final String SERIALIZED_NAME_TOTAL_WEIGHT = "totalWeight";
  @SerializedName(SERIALIZED_NAME_TOTAL_WEIGHT)
  private BigDecimal totalWeight;


  public V1beta2VerticalPodAutoscalerCheckpointStatusMemoryHistogram bucketWeights(Object bucketWeights) {

    this.bucketWeights = bucketWeights;
    return this;
  }

   /**
   * Map from bucket index to bucket weight.
   * @return bucketWeights
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Map from bucket index to bucket weight.")

  public Object getBucketWeights() {
    return bucketWeights;
  }


  public void setBucketWeights(Object bucketWeights) {
    this.bucketWeights = bucketWeights;
  }


  public V1beta2VerticalPodAutoscalerCheckpointStatusMemoryHistogram referenceTimestamp(Object referenceTimestamp) {

    this.referenceTimestamp = referenceTimestamp;
    return this;
  }

   /**
   * Reference timestamp for samples collected within this histogram.
   * @return referenceTimestamp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Reference timestamp for samples collected within this histogram.")

  public Object getReferenceTimestamp() {
    return referenceTimestamp;
  }


  public void setReferenceTimestamp(Object referenceTimestamp) {
    this.referenceTimestamp = referenceTimestamp;
  }


  public V1beta2VerticalPodAutoscalerCheckpointStatusMemoryHistogram totalWeight(BigDecimal totalWeight) {

    this.totalWeight = totalWeight;
    return this;
  }

   /**
   * Sum of samples to be used as denominator for weights from BucketWeights.
   * @return totalWeight
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Sum of samples to be used as denominator for weights from BucketWeights.")

  public BigDecimal getTotalWeight() {
    return totalWeight;
  }


  public void setTotalWeight(BigDecimal totalWeight) {
    this.totalWeight = totalWeight;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta2VerticalPodAutoscalerCheckpointStatusMemoryHistogram v1beta2VerticalPodAutoscalerCheckpointStatusMemoryHistogram = (V1beta2VerticalPodAutoscalerCheckpointStatusMemoryHistogram) o;
    return Objects.equals(this.bucketWeights, v1beta2VerticalPodAutoscalerCheckpointStatusMemoryHistogram.bucketWeights) &&
        Objects.equals(this.referenceTimestamp, v1beta2VerticalPodAutoscalerCheckpointStatusMemoryHistogram.referenceTimestamp) &&
        Objects.equals(this.totalWeight, v1beta2VerticalPodAutoscalerCheckpointStatusMemoryHistogram.totalWeight);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bucketWeights, referenceTimestamp, totalWeight);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta2VerticalPodAutoscalerCheckpointStatusMemoryHistogram {\n");
    sb.append("    bucketWeights: ").append(toIndentedString(bucketWeights)).append("\n");
    sb.append("    referenceTimestamp: ").append(toIndentedString(referenceTimestamp)).append("\n");
    sb.append("    totalWeight: ").append(toIndentedString(totalWeight)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

